version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: docquery-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DevPassword123!
      - POSTGRES_DB=docqueryservice
    ports:
      - "5432:5432"
    volumes:
      # If we want to data to persist, uncomment this. 
      # Leave it commented and database will be reset on each restart.
      # - postgres_data:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:
    driver: local