# Yarn security configuration following npm-security-best-practices
# https://github.com/bodadotsh/npm-security-best-practices

# Disable scripts to prevent malicious packages from running code during install
enableScripts: false

# Set minimum release age to 3 days (4320 minutes) to avoid recently published packages
# that might be compromised in supply chain attacks
npmMinimalAgeGate: 4320

# Use exact versions for security (equivalent to npm's save-exact)
defaultSemverRangePrefix: ""

# Enable strict SSL
enableStrictSsl: true

# Progress reporting
progressBarStyle: modern

# Network settings for security
httpTimeout: 60000
networkConcurrency: 10

# Use node-modules linker instead of PnP for better compatibility with existing tools
nodeLinker: node-modules