version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docquery-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - docquery-network
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend service (for local development/testing)
  backend:
    image: mcr.microsoft.com/dotnet/aspnet:9.0
    container_name: docquery-backend
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - ../backend-dotnet/bin/Release/net9.0/publish:/app
    working_dir: /app
    command: ["dotnet", "DocumentQueryService.Api.dll"]
    networks:
      - docquery-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  docquery-network:
    driver: bridge

volumes:
  nginx-cache:
    driver: local